### ISSUE TITLE
Явное сравнение с логическим значением

### ISSUE THREAD

**Issue by truenorthpaul** [AlexKozachenko/TitleCapitalizationTool#10]
Нет необходимости указывать проверку на равенство или неравенство логического значения со значением `true` или `false` явным образом. Другими словами вместо `if (isVisible == true)` стоит писать `if (isVisible)`, или вместо `if (isVisible == false)` можно написать `if (!isVisible)`.

Методы, в которых данное правило не соблюдается:
- `CapitalizationTool.CapitalizationTool.Capitalize`.

**Comment by AlexKozachenko** [comment]
не так понял ваше объяснение, что нельзя писать, допустим if(!value) если value небулевский тип, сделал вывод, что тру или фолз надо прописывать явно. теперь разобрался
