### ISSUE TITLE
Магические значения

### ISSUE THREAD

**Issue by truenorthpaul** [AlexKozachenko/TitleCapitalizationTool#11]
«Магические значения» не должны просто так встречаться в программном коде. Вместо них стоит использовать константы или перечисления с информативными идентификаторами или сопровождать программный код комментариями, описывающими причину использования данного магического значения и его смысл.

Значения, для которых данное правило не соблюдается:
- `4` (выражение `i += 4;` в методе `CapitalizationTool.CapitalizationTool.Capitalize`).
- `3` (выражение `Line = Line.Insert(i + 3, " ");` в методе `CapitalizationTool.CapitalizationTool.Capitalize`).

**Comment by AlexKozachenko** [comment]
исправил
