### ISSUE TITLE
Порядок объявления членов в типе

### ISSUE THREAD

**Issue by truenorthpaul** [AlexKozachenko/TitleCapitalizationTool#13]
При описании типа данных (класса, структуры или интерфейса) необходимо соблюдать следующий порядок объявления членов.
- Константы.
- Статические `readonly` поля.
- Статические поля.
- Объектные `readonly` поля.
- Объектные поля.
- Конструкторы.
- Финализатор.
- Индексаторы.
- Статические свойства.
- Объектные свойства.
- Статические события.
- Объектные события.
- Статические методы.
- Объектные методы.
- Операторы.

При этом каждая из перечисленных групп должна быть отделена одной пустой строкой от соседних. В пределах каждой группы члены должны быть расположены по алфавиту. Все виды методов должны быть также отделены одной пустой строкой от соседних методов.

Классы, в которых данное правило не соблюдается:
- `TitleCapitalizationTool.TitleCapitalizationTool`.

**Comment by AlexKozachenko** [comment]
исправлено

**Comment by truenorthpaul** [comment]
Методы не располагаются по алфавиту.

**Comment by AlexKozachenko** [comment]
С учетом спецификаторов доступа и типов возвратного значения надо сортировать или только по именам методов?

**Comment by AlexKozachenko** [comment]
правильно так:
private String[] emptyWords
private Char[] punctuationMarks

 public static void Main()

public void Сapitalize()
private Boolean IsEmptyWords(String line)
private Boolean IsPunctuationMarks(Char mark) ??

или так:
private Char[] punctuationMarks
private String[] emptyWords

public static void Main()

private Boolean IsEmptyWords(String line)
private Boolean IsPunctuationMarks(Char mark) 
public void Сapitalize()
??
