### ISSUE TITLE
Отступы между инициализаторами массива или коллекции

### ISSUE THREAD

**Issue by truenorthpaul** [AlexKozachenko/TitleCapitalizationTool#14]
При описании списка инициализаторов массива или коллекции, необходимо отделять элементы одним пробелом после запятой. Также фигурные скобки должны быть отделены одним пробелом от инициализаторов.

Поля, для которых данное правило не соблюдается:
- `TitleCapitalizationTool.TitleCapitalizationTool.emptyWords`.

**Comment by AlexKozachenko** [comment]
исправлено (в одном месте не было пробела)
