### ISSUE TITLE
Избыточность имен

### ISSUE THREAD

**Issue by truenorthpaul** [AlexKozachenko/TitleCapitalizationTool#15]
Нет необходимости включать в идентификатор название типа или другое название, указывающее слишком много лишней информации (например, массив). Другими словами вместо `string nameString` стоит писать `string name`, или вместо `int[] valuesArray` можно написать `int[] values`.

Переменные, для идентификаторов которых данное правило не соблюдется:
- `lineArray` (метод `TitleCapitalizationTool.TitleCapitalizationTool.Сapitalize`).

**Comment by AlexKozachenko** [comment]
исправил lineArray на substrings
