### ISSUE TITLE
Перекрытие пространства имен и типа

### ISSUE THREAD

**Issue by truenorthpaul** [AlexKozachenko/TitleCapitalizationTool#17]
Не стоит называть тип так же, как и пространство имен, в котором он находится. Это будет создавать неудобства при его использовании, так как идентификаторы будут перекрываться и у них будет разный приоритет для компилятора в различных ситуациях.

Классы, для которых данное правило не соблюдается:
- `TitleCapitalizationTool.TitleCapitalizationTool`.

**Comment by AlexKozachenko** [comment]
исправил namespace на Capitalization

**Comment by truenorthpaul** [comment]
С пространством имен как раз не было проблем, оно должно называться как проект. Надо исправить название типа и файла, в котором он находится.
