### ISSUE TITLE
Нарушение конвенции именования идентификаторов

### ISSUE THREAD

**Issue by truenorthpaul** [AlexKozachenko/TitleCapitalizationTool#5]
При создании идентификаторов необходимо придерживаться следующих конвенций именования:
- `camelCase` - переменные, поля, параметры.
- `PascalCase` - пространства имен, типы (классы, структуры и т.п.), методы, свойства, события.

Поля, для которых данное правило не соблюдается:
- `CapitalizationTool.CapitalizationTool.EmptyWords`.
- `CapitalizationTool.CapitalizationTool.PunctuationMarks`.

Параметры, для которых данное правило не соблюдается:
- `Line` (метод `CapitalizationTool.CapitalizationTool.IsEmptyWords`).
- `Mark` (метод `CapitalizationTool.CapitalizationTool.IsPunctuationMarks`).

Переменные, для которых данное правило не соблюдается:
- `FirstLetter` (метод `CapitalizationTool.CapitalizationTool.Capitalize`).
- `Line` (метод `CapitalizationTool.CapitalizationTool.Capitalize`).
- `Line1` (метод `CapitalizationTool.CapitalizationTool.Capitalize`).
- `TopCursorPosition` (метод `CapitalizationTool.CapitalizationTool.Capitalize`).
- `CapitalizationTool` (метод `CapitalizationTool.CapitalizationTool.Main`).

**Comment by AlexKozachenko** [comment]
исправил
