### ISSUE TITLE
Отступы между членами типа

### ISSUE THREAD

**Issue by truenorthpaul** [AlexKozachenko/TitleCapitalizationTool#6]
Между членами типа (поля, конструкторы, свойства, методы и т.п.) должны быть отступы в виде пустой строки. Отступы не стоит делать между каждыми двумя полями, константами и событиями.

Классы, в которых данное правило не соблюдается:
- `CapitalizationTool.CapitalizationTool`.

**Comment by AlexKozachenko** [comment]
исправлено
