### ISSUE TITLE
Неинформативные идентификаторы

### ISSUE THREAD

**Issue by truenorthpaul** [AlexKozachenko/TitleCapitalizationTool#8]
Идентификаторы должны быть информативны и описывать свое предназначение.

Переменные, для которых данное правило не соблюдается:
- `flag` (метод `CapitalizationTool.CapitalizationTool.IsEmptyWords`).
- `flag` (метод `CapitalizationTool.CapitalizationTool.IsPunctuationMarks`).
- `Line1` (метод `CapitalizationTool.CapitalizationTool.Capitalize`).

**Comment by AlexKozachenko** [comment]
исправил
